version: '3'
services:  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password #適宜自分のMySQLのパスワードにしてください
  web:
    build: .
    command: bundle exec rails s -e production
    volumes:
      - .:/voting
    depends_on:
      - db
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/voting/public
      - ./tmp:/voting/tmp
    depends_on:
      - web